name: Dev Docker Deploy

on:
  push:
    branches: ["develop"]

jobs:
  package_and_build:
    name: Log into dev server, build Docker image and run container
    runs-on: self-hosted
    environment: DEV
    steps:
      - name: Logging into server and executing prepared scripts
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ./deployment/front.sh DEV ${{ vars.RUNNING_PORT }} ${{ vars.REACT_APP_VERSION }} ${{ secrets.REACT_APP_API_URL }} 
